resolvers:
  observation_availability:
    type: "observation_availability"
    path: "/api/storage/resultData/getResultExistMap"
    method: "GET"
    params:
      lang: "{default_lang}"
    query_from_context:
      dataGroupId: "dataset_id"
    domain_by_action:
      query_one_dim_data: ["ONE_D"]
      query_time_domain: ["TWO_D_TD"]
      query_frequency_spectrum: ["TWO_D_FS"]
      query_order_spectrum: ["TWO_D_OS"]
      query_order_slice: ["TWO_D_OC"]
      query_cepstrum: ["TWO_D_CEP"]
      query_psychoacoustics: ["TWO_D_PS"]

  observation_indicators:
    type: "observation_indicators"
    default_endpoint:
      path: "/api/storage/config/listLineIndicatorsByResult"
      method: "POST"
      include_data_type: true
      params:
        lang: "{default_lang}"
      response:
        items_path: "data"
        value_key: "indicatorName"
        label_field: "indicatorIndex"
    endpoints_by_domain:
      ONE_D:
        path: "/api/storage/config/listOneIndicatorsByResult"
        method: "POST"
        params:
          lang: "{default_lang}"
        response:
          items_path: "data"
          value_key: "name"
          label_field: "index"
      TWO_D_OC:
        path: "/api/storage/config/listMultiLineIndicatorsByResult"
        method: "POST"
        include_data_type: true
        params:
          lang: "{default_lang}"
        response:
          items_path: "data"
          value_key: "indicatorName"
          label_field: "indicatorIndex"
    domain_by_action:
      query_one_dim_data: ["ONE_D"]
      query_time_domain: ["TWO_D_TD"]
      query_frequency_spectrum: ["TWO_D_FS"]
      query_order_spectrum: ["TWO_D_OS"]
      query_order_slice: ["TWO_D_OC"]
      query_cepstrum: ["TWO_D_CEP"]
      query_psychoacoustics: ["TWO_D_PS"]
