query_one_dim_data:
  intent_names:
    - "task.nvh.data_observation.batch.one_dim_data"
  title: "Query one dim data"
  risk_level: "low"
  requires_confirmation: false
  required_slots:
    - "sensors"
    - "test_segments"
    - "indicator_names"
  optional_slots: []

query_time_domain:
  intent_names:
    - "task.nvh.data_observation.batch.time_domain"
  title: "Query time domain"
  risk_level: "low"
  requires_confirmation: false
  required_slots:
    - "sensors"
    - "test_segments"
    - "indicator_names"
  optional_slots: []

query_frequency_spectrum:
  intent_names:
    - "task.nvh.data_observation.batch.frequency_spectrum"
  title: "Query frequency spectrum"
  risk_level: "low"
  requires_confirmation: false
  required_slots:
    - "sensors"
    - "test_segments"
    - "indicator_names"
  optional_slots: []

query_order_spectrum:
  intent_names:
    - "task.nvh.data_observation.batch.order_spectrum"
  title: "Query order spectrum"
  risk_level: "low"
  requires_confirmation: false
  required_slots:
    - "sensors"
    - "test_segments"
    - "indicator_names"
  optional_slots: []

query_order_slice:
  intent_names:
    - "task.nvh.data_observation.batch.order_slice"
  title: "Query order slice"
  risk_level: "low"
  requires_confirmation: false
  required_slots:
    - "sensors"
    - "test_segments"
    - "indicator_names"
  optional_slots: []

query_cepstrum:
  intent_names:
    - "task.nvh.data_observation.batch.cepstrum"
  title: "Query cepstrum"
  risk_level: "low"
  requires_confirmation: false
  required_slots:
    - "sensors"
    - "test_segments"
    - "indicator_names"
  optional_slots: []

query_psychoacoustics:
  intent_names:
    - "task.nvh.data_observation.batch.psychoacoustics"
  title: "Query psychoacoustics"
  risk_level: "low"
  requires_confirmation: false
  required_slots:
    - "sensors"
    - "test_segments"
    - "indicator_names"
  optional_slots: []
